spring:
  application:
    name: Track_It
    version: 0.5-alpha
    description: A customizable next-generation project tracker
  profiles:
    active: dev  # <--- Se non dico nulla, parti in DEV

  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 300 # 5m
    refreshTokenExpiration: 604800 # 7d

app:
  cors:
    allowed-origins: http://localhost:3000, http://localhost:5173, http://127.0.0.1:3000, http://127.0.0.1:5173

# Documentazione API Restfull
springdoc:
  swagger-ui:
    path: /api/swagger/doc.html
